CREATE TYPE [dbo].[GrisRawWeightDataTvp] AS TABLE (
    [ID]                  BIGINT         NULL,
    [Dato]                DATETIME       NULL,
    [DeviceID]            NVARCHAR (50)  NULL,
    [VejeholdNr]          SMALLINT       NULL,
    [FoderVaegtID]        INT            NULL,
    [VejeholdID]          INT            NULL,
    [RawHourData]         NVARCHAR (MAX) NULL,
    [VandData]            NVARCHAR (MAX) NULL,
    [IFVersion]           SMALLINT       NULL,
    [ModtagetStart]       DATETIME       NULL,
    [ModtagetSlut]        DATETIME       NULL,
    [FoderFraVaegt]       INT            NULL,
    [FoderTotal]          INT            NULL,
    [FoderManuel]         INT            NULL,
    [FoderForbrug]        INT            NULL,
    [VandTotal]           INT            NULL,
    [VandForbrug]         INT            NULL,
    [MixNr]               SMALLINT       NULL,
    [FoderMixVersionID]   INT            NULL,
    [Vaegt]               INT            NULL,
    [Antal]               INT            NULL,
    [TilvaekstGramPrGris] INT            NULL,
    [AntalGalte]          SMALLINT       NULL,
    [AntalSogrise]        SMALLINT       NULL,
    [VejeholdID1]         INT            NULL);

