CREATE TYPE [dbo].[MinkVejeholdTvp] AS TABLE (
    [ID]                       INT            NULL,
    [DeviceID]                 NVARCHAR (25)  NULL,
    [KundeID]                  INT            NULL,
    [Navn]                     NVARCHAR (50)  NULL,
    [StartDato]                DATETIME       NULL,
    [SlutDato]                 DATETIME       NULL,
    [Aar]                      INT            NULL,
    [DyreTypeID]               INT            NULL,
    [HoldTypeID]               SMALLINT       NULL,
    [Beskrivelse]              NVARCHAR (MAX) NULL,
    [RaekkeID]                 INT            NULL,
    [Bur1Nr]                   SMALLINT       NULL,
    [Bur2Nr]                   SMALLINT       NULL,
    [Bur3Nr]                   SMALLINT       NULL,
    [Bur4Nr]                   SMALLINT       NULL,
    [Bur5Nr]                   SMALLINT       NULL,
    [Bur6Nr]                   SMALLINT       NULL,
    [SidstRettet]              DATETIME       NULL,
    [SidstRettetAfBrugerID]    INT            NULL,
    [Slettet]                  BIT            NULL,
    [Placering]                INT            NULL,
    [SlankeKurveID]            INT            NULL,
    [FoderStyrkeNedStartDato]  DATETIME       NULL,
    [HanGnsTilv7dage]          SMALLINT       NULL,
    [HunGnsTilv7dage]          SMALLINT       NULL,
    [HanGnsTilv2og3dage]       SMALLINT       NULL,
    [HunGnsTilv2og3dage]       SMALLINT       NULL,
    [HanGnsTilvIgaar]          SMALLINT       NULL,
    [HunGnsTilvIgaar]          SMALLINT       NULL,
    [HanGnsSidste3dageVaegtet] SMALLINT       NULL,
    [HunGnsSidste3dageVaegtet] SMALLINT       NULL,
    [SidstOnline]              DATETIME       NULL,
    [Overvaagning]             BIT            NULL,
    [GensendFraID]             INT            NULL,
    [OpsaetningData]           NVARCHAR (MAX) NULL,
    [OpsaetningModtaget]       DATETIME       NULL,
    [OrdreNr]                  INT            NULL,
    [OldID]                    INT            NULL,
    [SlutDatoKopi]             DATETIME       NULL);

