CREATE TYPE [dbo].[MinkHaendelseTvp] AS TABLE (
    [ID]                    INT              NULL,
    [KundeID]               INT              NULL,
    [BedriftID]             INT              NULL,
    [HusID]                 INT              NULL,
    [RaekkeID]              INT              NULL,
    [BurNr]                 INT              NULL,
    [MinkVaegtholdID]       INT              NULL,
    [MinkHaendelseTypeID]   INT              NULL,
    [AntalHan]              INT              NULL,
    [AntalHun]              INT              NULL,
    [AntalDreng]            INT              NULL,
    [AntalPige]             INT              NULL,
    [MedicinID]             INT              NULL,
    [Bemaerkning]           NVARCHAR (MAX)   NULL,
    [DyreTypeID]            INT              NULL,
    [AarsagID]              INT              NULL,
    [Dato]                  DATETIME         NULL,
    [Oprettet]              DATETIME         NULL,
    [SeasonID]              INT              NULL,
    [AntalDyr]              INT              NULL,
    [SidstRettetAfBrugerID] INT              NULL,
    [SidstRettet]           DATETIME         NULL,
    [Slettet]               BIT              NULL,
    [BrugerDeviceID]        INT              NULL,
    [ObjektGuid]            UNIQUEIDENTIFIER NULL,
    [DeviceID]              NVARCHAR (50)    NULL,
    [Hanner]                INT              NULL,
    [Hunner]                INT              NULL,
    [Drenge]                INT              NULL,
    [Piger]                 INT              NULL,
    [ErAflivet]             BIT              NULL);

