CREATE TYPE [dbo].[MinkRawWeightDataTvp] AS TABLE (
    [ID]                BIGINT         NULL,
    [Dato]              DATETIME       NULL,
    [DeviceID]          NVARCHAR (25)  NULL,
    [CelleNr]           SMALLINT       NULL,
    [VaegtholdID]       INT            NULL,
    [Data]              NVARCHAR (MAX) NULL,
    [Antal]             SMALLINT       NULL,
    [HanVaegt]          SMALLINT       NULL,
    [HunVaegt]          SMALLINT       NULL,
    [HanVaegtKorigeret] SMALLINT       NULL,
    [HunVaegtKorigeret] SMALLINT       NULL,
    [IFVersion]         SMALLINT       NULL,
    [ModtagetStart]     DATETIME       NULL,
    [ModtagetSlut]      DATETIME       NULL,
    [HanBeregnet]       SMALLINT       NULL,
    [HunBeregnet]       SMALLINT       NULL,
    [HanGnsTilv]        SMALLINT       NULL,
    [HunGnsTilv]        SMALLINT       NULL,
    [UgeAarID]          INT            NULL,
    [Slettet]           BIT            NULL);

