CREATE TYPE [dbo].[MinkFoderVuderingTvp] AS TABLE (
    [ID]                    INT              NULL,
    [KundeID]               INT              NULL,
    [FoderCentralID]        INT              NULL,
    [BedriftID]             INT              NULL,
    [Dato]                  DATETIME         NULL,
    [SeasonID]              INT              NULL,
    [ForTyndt]              BIT              NULL,
    [ForTykt]               BIT              NULL,
    [Lugter]                BIT              NULL,
    [Styrke]                INT              NULL,
    [NaesteLeveringMaengde] INT              NULL,
    [LeveretMaengde]        INT              NULL,
    [Maengde]               INT              NULL,
    [FoderPrDyr]            INT              NULL,
    [BrugerDeviceID]        INT              NULL,
    [SidstRettet]           DATETIME         NULL,
    [ObjektGuid]            UNIQUEIDENTIFIER NULL,
    [SidstRettetAfBrugerID] INT              NULL,
    [Slettet]               BIT              NULL,
    [DeviceID]              NVARCHAR (50)    NULL,
    [BemaerkningCentral]    NVARCHAR (MAX)   NULL,
    [Bemaerkning]           NVARCHAR (MAX)   NULL,
    [AntalDyr]              INT              NULL);

