CREATE TYPE [dbo].[RawFeedDataTvp] AS TABLE (
    [ID]                   BIGINT         NULL,
    [UniqueID]             NVARCHAR (50)  NULL,
    [VejeholdNr]           SMALLINT       NULL,
    [LbNr]                 SMALLINT       NULL,
    [KundeID]              INT            NULL,
    [IFVersion]            SMALLINT       NULL,
    [Dato]                 DATETIME       NULL,
    [Data]                 NVARCHAR (MAX) NULL,
    [Modtaget]             DATETIME       NULL,
    [Importeret]           BIT            NULL,
    [TimeNrID]             SMALLINT       NULL,
    [VejeholdID]           INT            NULL,
    [Foder]                SMALLINT       NULL,
    [Vand]                 SMALLINT       NULL,
    [Mix1]                 SMALLINT       NULL,
    [Mix2]                 SMALLINT       NULL,
    [Mix3]                 SMALLINT       NULL,
    [Mix4]                 SMALLINT       NULL,
    [Mix5]                 SMALLINT       NULL,
    [Mix6]                 SMALLINT       NULL,
    [Mix7]                 SMALLINT       NULL,
    [FoderDelta]           INT            NULL,
    [VandDelta]            SMALLINT       NULL,
    [Mix1Delta]            INT            NULL,
    [Mix2Delta]            INT            NULL,
    [Mix3Delta]            INT            NULL,
    [Mix4Delta]            INT            NULL,
    [Mix5Delta]            INT            NULL,
    [Mix6Delta]            INT            NULL,
    [Mix7Delta]            INT            NULL,
    [AktivMixNr]           SMALLINT       NULL,
    [FoderMixVersionID]    INT            NULL,
    [SenesteVaegt]         SMALLINT       NULL,
    [AntalVedSenesteVaegt] SMALLINT       NULL,
    [FoderEffektivitet]    SMALLINT       NULL,
    [VægtJustering]        SMALLINT       NULL,
    [AntalJustering]       SMALLINT       NULL,
    [UltimoAntal]          SMALLINT       NULL,
    [UltimoVaegt]          SMALLINT       NULL);

