CREATE TYPE [dbo].[VejeholdDataTvp] AS TABLE (
    [ID]                   BIGINT         NULL,
    [UniqueID]             NVARCHAR (50)  NULL,
    [VejeholdNr]           SMALLINT       NULL,
    [LbNr]                 SMALLINT       NULL,
    [KundeID]              INT            NULL,
    [IFVersion]            SMALLINT       NULL,
    [Dato]                 DATETIME       NULL,
    [Data]                 NVARCHAR (MAX) NULL,
    [Modtaget]             DATETIME       NULL,
    [Importeret]           BIT            NULL,
    [TimeNrID]             SMALLINT       NULL,
    [VejeholdID]           INT            NULL,
    [Foder]                INT            NULL,
    [Vand]                 INT            NULL,
    [Mix1]                 INT            NULL,
    [Mix2]                 INT            NULL,
    [Mix3]                 INT            NULL,
    [Mix4]                 INT            NULL,
    [Mix5]                 INT            NULL,
    [Mix6]                 INT            NULL,
    [Mix7]                 INT            NULL,
    [FoderDelta]           INT            NULL,
    [VandDelta]            INT            NULL,
    [Mix1Delta]            INT            NULL,
    [Mix2Delta]            INT            NULL,
    [Mix3Delta]            INT            NULL,
    [Mix4Delta]            INT            NULL,
    [Mix5Delta]            INT            NULL,
    [Mix6Delta]            INT            NULL,
    [Mix7Delta]            INT            NULL,
    [FoderMixVersionID]    INT            NULL,
    [VejeholdVejningID]    INT            NULL,
    [ErFoderskift]         BIT            NULL,
    [FoderGramTimeDyr]     DECIMAL (8, 4) NULL,
    [VandMlTimeDyr]        DECIMAL (8, 4) NULL,
    [TilvaekstGramTimeDyr] DECIMAL (8, 4) NULL,
    [Redigeret]            BIT            NULL,
    [Vaegt]                INT            NULL,
    [AntalGalte]           SMALLINT       NULL,
    [AntalSogrise]         SMALLINT       NULL,
    [MixNr]                SMALLINT       NULL,
    [TilvaegstGramTimeDyr] DECIMAL (8, 4) NULL,
    [CopyToNew]            BIT            NULL);

