CREATE TYPE [dbo].[VejeholdVejningTvp] AS TABLE (
    [ID]                    INT              NULL,
    [KundeID]               INT              NULL,
    [VejeholdID]            INT              NULL,
    [Dato]                  DATETIME         NULL,
    [StartLbNr]             SMALLINT         NULL,
    [SlutLbNr]              SMALLINT         NULL,
    [StartAntalGalte]       SMALLINT         NULL,
    [SlutAntalGalte]        SMALLINT         NULL,
    [StartAntalSogrise]     SMALLINT         NULL,
    [SlutAntalSogrise]      SMALLINT         NULL,
    [StartVaegt]            INT              NULL,
    [SlutVaegt]             INT              NULL,
    [Bemaerkning]           NVARCHAR (MAX)   NULL,
    [FoderMixVersionID]     INT              NULL,
    [Foder]                 INT              NULL,
    [DagligTilvaekstGram]   INT              NULL,
    [EffektivitetFoder]     FLOAT (53)       NULL,
    [EffektivitetGenerelt]  FLOAT (53)       NULL,
    [Oprettet]              DATETIME         NULL,
    [BrugerDeviceID]        INT              NULL,
    [SidstRettet]           DATETIME         NULL,
    [SidstRettetAfBrugerID] INT              NULL,
    [Slettet]               BIT              NULL,
    [GnsFoderForbrugGram]   INT              NULL,
    [AkkTilv]               INT              NULL,
    [FEsvDyrDag]            DECIMAL (7, 2)   NULL,
    [FEsvKgTilv]            DECIMAL (7, 2)   NULL,
    [AkkFEsvKgTilv]         DECIMAL (7, 2)   NULL,
    [DkrKgTilv]             DECIMAL (7, 2)   NULL,
    [KgM2]                  INT              NULL,
    [FoderTotal]            INT              NULL,
    [GnsTilvaekstGram]      INT              NULL,
    [SlutAntal]             INT              NULL,
    [DageImellem]           SMALLINT         NULL,
    [SlutDag]               SMALLINT         NULL,
    [SlutAlder]             SMALLINT         NULL,
    [BeregningLog]          NVARCHAR (MAX)   NULL,
    [ManFoder]              INT              NULL,
    [ManVand]               INT              NULL,
    [ManMixNr]              SMALLINT         NULL,
    [ObjektGuid]            UNIQUEIDENTIFIER NULL,
    [DeviceID]              NVARCHAR (50)    NULL);

