/**
 * BilligKwh API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConsumptionDto { 
    id?: number;
    date?: string;
    deviceId?: number;
    lastUpdatedUtc?: string;
    h00?: number;
    h23?: number;
    c00?: number;
    c01?: number;
    c02?: number;
    c03?: number;
    c04?: number;
    c05?: number;
    c06?: number;
    c07?: number;
    c08?: number;
    c09?: number;
    c10?: number;
    c11?: number;
    c12?: number;
    c13?: number;
    c14?: number;
    c15?: number;
    c16?: number;
    c17?: number;
    c18?: number;
    c19?: number;
    c20?: number;
    c21?: number;
    c22?: number;
    c23?: number;
}

