/**
 * BilligKwh API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomerModel { 
    id?: number;
    publicId?: string;
    name?: string | null;
    address?: string | null;
    countryId?: number;
    active?: boolean;
    dateCreatedUtc?: string;
    dateDeletedUtc?: string | null;
    deleted?: boolean;
    dateLastUpdatedUtc?: string;
    timeZoneId?: string | null;
    languageId?: number;
    companyRegistrationId?: string | null;
    lastEditedUtc?: string;
}

