/**
 * BilligKwh API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DokumentDto { 
    oprettet?: string;
    brugernavn?: string | null;
    fuldtNavn?: string | null;
    base64Data?: string | null;
    filData?: string | null;
    nullableInt?: number | null;
}

