/**
 * BilligKwh API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ElTavleDto { 
    id?: number;
    objektGuid?: string;
    kundeID?: number;
    kundeNavn?: string | null;
    landID?: number;
    adresse?: string | null;
    kommentar?: string | null;
    rekvisition?: string | null;
    oprettetAf?: string | null;
    oprettetAfBrugerID?: number;
    beregnetDato?: string;
    bestiltDato?: string | null;
    komponenterPris?: number;
    komponenterInstallatoer?: number;
    timeAntal?: number;
    timePris?: number;
    dbFaktor?: number;
    prisInclTimerOgDB?: number;
    fragt?: number;
    optjentBonus?: number | null;
    udbetaltBonus?: number | null;
    sidstRettet?: string;
    tavlefabrikatID?: number;
    moduler?: number;
    slettet?: boolean;
    kabinetModuler?: number;
    antal?: number;
    nettoPris?: number;
    initialRabat?: boolean;
    bonusGivende?: boolean;
    typeID?: number;
    aar?: number | null;
    loebeNr?: number | null;
    economicCustomerNumber?: number | null;
    economicOrderNumber?: number | null;
    economicDraftInvoiceNumber?: number | null;
    economicBookedInvoiceNumber?: number | null;
    tavleNr?: string | null;
    economicSidstRettet?: string | null;
    maerkeStroem?: string | null;
    kapslingsKlasse?: string | null;
    driftsSpaending?: string | null;
    maxKortslutningsStroem?: string | null;
    bonusTilgode?: number;
    billeder?: number | null;
    installeretEffekt?: number | null;
    maxEffekt?: number | null;
}

