/**
 * BilligKwh API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PrintDto { 
    id?: number;
    printId?: string | null;
    kundeId?: number | null;
    oprettetDatoUtc?: string;
    sidsteKontaktDatoUtc?: string;
    lokation?: string | null;
    slettet?: string | null;
    kommentar?: string | null;
}

