/**
 * BilligKwh API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScheduleDto { 
    id?: number;
    date?: string;
    h00?: number;
    h01?: number;
    h02?: number;
    h03?: number;
    h04?: number;
    h05?: number;
    h06?: number;
    h07?: number;
    h08?: number;
    h09?: number;
    h10?: number;
    h11?: number;
    h12?: number;
    h13?: number;
    h14?: number;
    h15?: number;
    h16?: number;
    h17?: number;
    h18?: number;
    h19?: number;
    h20?: number;
    h21?: number;
    h22?: number;
    h23?: number;
    p00?: number;
    p01?: number;
    p02?: number;
    p03?: number;
    p04?: number;
    p05?: number;
    p06?: number;
    p07?: number;
    p08?: number;
    p09?: number;
    p10?: number;
    p11?: number;
    p12?: number;
    p13?: number;
    p14?: number;
    p15?: number;
    p16?: number;
    p17?: number;
    p18?: number;
    p19?: number;
    p20?: number;
    p21?: number;
    p22?: number;
    p23?: number;
}

