/**
 * BilligKwh API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScheduleDto { 
    id?: number;
    date?: string;
    h00?: boolean;
    h01?: boolean;
    h02?: boolean;
    h03?: boolean;
    h04?: boolean;
    h05?: boolean;
    h06?: boolean;
    h07?: boolean;
    h08?: boolean;
    h09?: boolean;
    h10?: boolean;
    h11?: boolean;
    h12?: boolean;
    h13?: boolean;
    h14?: boolean;
    h15?: boolean;
    h16?: boolean;
    h17?: boolean;
    h18?: boolean;
    h19?: boolean;
    h20?: boolean;
    h21?: boolean;
    h22?: boolean;
    h23?: boolean;
}

