/**
 * BilligKwh API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SektionElKomponentDto { 
    id?: number;
    elTavleSektionID?: number;
    sektion?: number;
    elTavleID?: number;
    line?: number;
    modul?: number;
    komponentNavn?: string | null;
    komponentID?: number;
    kategoriID?: number;
    navn?: string | null;
    placering?: number;
    erExtraDisp?: boolean;
    serverNavn?: string | null;
    angivetNavn?: boolean;
    bruttoPris?: number;
}

