/**
 * BilligKwh API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserEditModel { 
    id?: number;
    customerId?: number;
    email?: string | null;
    name?: string | null;
    phone?: string | null;
    languageId?: number;
    countryId?: number;
    newPassword?: string | null;
    administrator?: boolean;
    deleted?: boolean;
}

