/**
 * BilligKwh API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserModel { 
    id?: number;
    customerId?: number;
    email?: string | null;
    firstname?: string | null;
    lastname?: string | null;
    department?: string | null;
    phone?: string | null;
    mobile?: string | null;
    languageId?: number;
    deleted?: boolean;
    countryId?: number;
    timezoneId?: string | null;
    resetPhone?: number | null;
    isSuperAdmin?: boolean;
    impersonatingUser?: UserModel;
}

