CREATE TABLE [dbo].[Consumptions] (
    [Id]             INT      IDENTITY (1, 1) NOT NULL,
    [Date]           DATE     NOT NULL,
    [DeviceId]       INT      NOT NULL,
    [LastUpdatedUtc] DATETIME NOT NULL,
    [H00]            BigInt      NOT NULL,
    [H01]            BigInt      NOT NULL,
    [H02]            BigInt      NOT NULL,
    [H03]            BigInt      NOT NULL,
    [H04]            BigInt      NOT NULL,
    [H05]            BigInt      NOT NULL,
    [H06]            BigInt      NOT NULL,
    [H07]            BigInt      NOT NULL,
    [H08]            BigInt      NOT NULL,
    [H09]            BigInt      NOT NULL,
    [H10]            BigInt      NOT NULL,
    [H11]            BigInt      NOT NULL,
    [H12]            BigInt      NOT NULL,
    [H13]            BigInt      NOT NULL,
    [H14]            BigInt      NOT NULL,
    [H15]            BigInt      NOT NULL,
    [H16]            BigInt      NOT NULL,
    [H17]            BigInt      NOT NULL,
    [H18]            BigInt      NOT NULL,
    [H19]            BigInt      NOT NULL,
    [H20]            BigInt      NOT NULL,
    [H21]            BigInt      NOT NULL,
    [H22]            BigInt      NOT NULL,
    [H23]            BigInt      NOT NULL,
    CONSTRAINT [PK_Consumptions] PRIMARY KEY CLUSTERED ([Id] ASC)
);

