CREATE TABLE [dbo].[Consumptions] (
    [Id]             INT      IDENTITY (1, 1) NOT NULL,
    [Date]           DATE     NOT NULL,
    [DeviceId]       INT      NOT NULL,
    [LastUpdatedUtc] DATETIME NOT NULL,
    [H00]            BIGINT   NOT NULL,
    [H01]            BIGINT   NOT NULL,
    [H02]            BIGINT   NOT NULL,
    [H03]            BIGINT   NOT NULL,
    [H04]            BIGINT   NOT NULL,
    [H05]            BIGINT   NOT NULL,
    [H06]            BIGINT   NOT NULL,
    [H07]            BIGINT   NOT NULL,
    [H08]            BIGINT   NOT NULL,
    [H09]            BIGINT   NOT NULL,
    [H10]            BIGINT   NOT NULL,
    [H11]            BIGINT   NOT NULL,
    [H12]            BIGINT   NOT NULL,
    [H13]            BIGINT   NOT NULL,
    [H14]            BIGINT   NOT NULL,
    [H15]            BIGINT   NOT NULL,
    [H16]            BIGINT   NOT NULL,
    [H17]            BIGINT   NOT NULL,
    [H18]            BIGINT   NOT NULL,
    [H19]            BIGINT   NOT NULL,
    [H20]            BIGINT   NOT NULL,
    [H21]            BIGINT   NOT NULL,
    [H22]            BIGINT   NOT NULL,
    [H23]            BIGINT   NOT NULL,
    [C00]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C01]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C02]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C03]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C04]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C05]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C06]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C07]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C08]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C09]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C10]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C11]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C12]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C13]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C14]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C15]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C16]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C17]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C18]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C19]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C20]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C21]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C22]            Decimal(5,1)  NOT NULL DEFAULT -1,
    [C23]            Decimal(5,1)  NOT NULL DEFAULT -1,
    CONSTRAINT [PK_Consumption] PRIMARY KEY CLUSTERED ([Id] ASC)
);



