CREATE TABLE [dbo].[Helpdesk] (
    [ID]                    INT            IDENTITY (1, 1) NOT NULL,
    [Overskrift]            NVARCHAR (100) NOT NULL,
    [KundeID]               INT            NOT NULL,
    [OprettetAfBrugerID]    INT            NOT NULL,
    [Oprettet]              DATETIME       NOT NULL,
    [ModulID]               INT            CONSTRAINT [DF_Table_1_StylesheetID] DEFAULT ((1)) NOT NULL,
    [PriotetID]             INT            NOT NULL,
    [AnsvarligBrugerID]     INT            CONSTRAINT [DF_Helpdesk_AnsvarligBrugerID] DEFAULT ((0)) NOT NULL,
    [UdforesAfBrugerID]     INT            CONSTRAINT [DF_Helpdesk_UdforesAfBrugerID] DEFAULT ((0)) NOT NULL,
    [StatusID]              INT            NOT NULL,
    [StatusInternID]        INT            CONSTRAINT [DF_Helpdesk_StatusInternID] DEFAULT ((0)) NOT NULL,
    [SidstRettet]           DATETIME       NOT NULL,
    [SidstRettetAfBrugerID] INT            NOT NULL,
    [KundeAfsluttet]        BIT            NOT NULL,
    [Deadline]              DATETIME       NULL,
    [HelpdeskProjektID]     INT            CONSTRAINT [DF_Helpdesk_HelpdeskProjektID] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Helpdesk] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Helpdesk_AnsvarligBruger] FOREIGN KEY ([AnsvarligBrugerID]) REFERENCES [dbo].[Bruger] ([ID]),
    CONSTRAINT [FK_Helpdesk_HelpdeskProjekt] FOREIGN KEY ([HelpdeskProjektID]) REFERENCES [dbo].[HelpdeskProjekt] ([ID]),
    CONSTRAINT [FK_Helpdesk_Kunde] FOREIGN KEY ([KundeID]) REFERENCES [dbo].[Kunde] ([ID]),
    CONSTRAINT [FK_Helpdesk_Modul] FOREIGN KEY ([ModulID]) REFERENCES [dbo].[Modul] ([ID]),
    CONSTRAINT [FK_Helpdesk_OprettetAfBruger] FOREIGN KEY ([OprettetAfBrugerID]) REFERENCES [dbo].[Bruger] ([ID]),
    CONSTRAINT [FK_Helpdesk_Priotet] FOREIGN KEY ([PriotetID]) REFERENCES [dbo].[ListePost] ([ID]),
    CONSTRAINT [FK_Helpdesk_SidstRettetAfBruger] FOREIGN KEY ([SidstRettetAfBrugerID]) REFERENCES [dbo].[Bruger] ([ID]),
    CONSTRAINT [FK_Helpdesk_Status] FOREIGN KEY ([StatusID]) REFERENCES [dbo].[ListePost] ([ID]),
    CONSTRAINT [FK_Helpdesk_StatusIntern] FOREIGN KEY ([StatusInternID]) REFERENCES [dbo].[ListePost] ([ID]),
    CONSTRAINT [FK_Helpdesk_UdforesAfBruger] FOREIGN KEY ([UdforesAfBrugerID]) REFERENCES [dbo].[Bruger] ([ID])
);

