CREATE TABLE [dbo].[SprogLabel] (
    [ID]                           INT            NOT NULL,
    [TypeID]                       INT            CONSTRAINT [DF_SprogLabel_TypeID_1] DEFAULT ((1)) NOT NULL,
    [Bemærkning]                   NVARCHAR (MAX) COLLATE SQL_Danish_Pref_CP1_CI_AS CONSTRAINT [DF_SprogLabel_Bemærkning_1] DEFAULT ('') NOT NULL,
    [Tekst]                        NVARCHAR (MAX) NOT NULL,
    [Norsk]                        NVARCHAR (MAX) CONSTRAINT [DF_SprogLabel_Norsk] DEFAULT ('') NOT NULL,
    [Svensk]                       NVARCHAR (MAX) CONSTRAINT [DF_SprogLabel_Svensk] DEFAULT ('') NOT NULL,
    [Engelsk]                      NVARCHAR (MAX) CONSTRAINT [DF_SprogLabel_Engelsk] DEFAULT ('') NOT NULL,
    [Tysk]                         NVARCHAR (MAX) CONSTRAINT [DF_SprogLabel_Tysk] DEFAULT ('') NOT NULL,
    [Graesk]                       NVARCHAR (MAX) CONSTRAINT [DF_SprogLabel_Graesk] DEFAULT ('') NOT NULL,
    [Kinesisk]                     NVARCHAR (MAX) CONSTRAINT [DF_SprogLabel_Graesk1] DEFAULT ('') NOT NULL,
    [Mobile]                       BIT            CONSTRAINT [DF_SprogLabel_Mobile] DEFAULT ((0)) NULL,
    [InitialMobile]                BIT            NULL,
    [SidstRettet]                  DATETIME       CONSTRAINT [DF_SprogLabel_SidstRettet] DEFAULT (getdate()) NOT NULL,
    [Slettet]                      BIT            NULL,
    [Fil]                          NVARCHAR (250) NULL,
    [DanskSidstRettetAfBrugerID]   INT            NULL,
    [NorskSidstRettetAfBrugerID]   INT            NULL,
    [SvenskSidstRettetAfBrugerID]  INT            NULL,
    [EngelskSidstRettetAfBrugerID] INT            NULL,
    [TyskSidstRettetAfBrugerID]    INT            NULL,
    [GraeskSidstRettetAfBrugerID]  INT            NULL,
    [Moduler]                      NVARCHAR (MAX) COLLATE SQL_Danish_Pref_CP1_CI_AS NULL,
    [DanskSidstRettetUtc]          DATETIME       NULL,
    [NorskSidstRettetUtc]          DATETIME       NULL,
    [SvenskSidstRettetUtc]         DATETIME       NULL,
    [EngelskSidstRettetUtc]        DATETIME       NULL,
    [TyskSidstRettetUtc]           DATETIME       NULL,
    [GraeskSidstRettetUtc]         DATETIME       NULL,
    [KinesiskSidstRettetUtc]       DATETIME       NULL,
    [Brugt]                        INT            CONSTRAINT [DF_SprogLabel_Brugt] DEFAULT ((0)) NOT NULL,
    [L4TS]                         INT            NULL,
    CONSTRAINT [PK_SprogLabel] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

