CREATE TABLE [dbo].[Users] (
    [Id]                               INT              IDENTITY (1, 1) NOT NULL,
    [CustomerId]                       INT              CONSTRAINT [DF_Users_CurrentCustomerId] DEFAULT ((0)) NOT NULL,
    [Email]                            NVARCHAR (256)   NOT NULL,
    [Name]                             NVARCHAR (500)   NULL,
    [Administrator]                    BIT              CONSTRAINT [DF_Users_ErAdministrator] DEFAULT ((0)) NOT NULL,
    [SystemAdministrator]              BIT              CONSTRAINT [DF_Users_SystemAdministrator] DEFAULT ((0)) NOT NULL,
    [Password]                         NVARCHAR (200)   NOT NULL,
    [PasswordSalt]                     NVARCHAR (24)    NULL,
    [FailedLoginCount]                 SMALLINT         NOT NULL,
    [IsLockedOut]                      BIT              NOT NULL,
    [PasswordResetToken]               UNIQUEIDENTIFIER NULL,
    [ResetPhone]                       BIGINT           NULL,
    [DatePasswordResetTokenExpiresUtc] DATETIME         NULL,
    [ReceiveNewsletter]                BIT              CONSTRAINT [DF_UserLogins_ReceiveNewsletter] DEFAULT ((0)) NOT NULL,
    [DateCreatedUtc]                   DATETIME         CONSTRAINT [DF_Users_DateCreatedUtc] DEFAULT (getutcdate()) NOT NULL,
    [Deleted]                          BIT              CONSTRAINT [DF_Users_Deleted] DEFAULT ((0)) NOT NULL,
    [DateDeletedUtc]                   DATETIME         NULL,
    [DateLastLoginUtc]                 DATETIME         NULL,
    [DateLastFailedLoginUtc]           DATETIME         NULL,
    [LanguageId]                       INT              CONSTRAINT [DF_Users_LanguageId] DEFAULT ((1)) NOT NULL,
    [TimeZoneId]                       NVARCHAR (100)   NULL,
    [CountryId]                        INT              CONSTRAINT [DF_Users_CountryId] DEFAULT ((1)) NOT NULL,
    [ImpersonatingUserId]              INT              NULL,
    [DateLastUpdatedUtc]               DATETIME         CONSTRAINT [DF__Users__DateLastU__2F2FFC0C] DEFAULT (getutcdate()) NULL,
    [PersonDataAcceptDate]             DATETIME         NULL,
    CONSTRAINT [PK_Login] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

